# 공통 설정

# Spring 설정
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: 'classpath:/static/'
  http:
    encoding:
      charset: UTF-8
      force: true