# Spring 설정
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  resources:
    static-locations: 'classpath:/app/dist/'
  mvc:
    static-path-pattern: /resources/**
  thymeleaf:
    enabled: true
    prefix: 'classpath:/app/dist/'
    suffix: .html
